services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-prod

  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: app
    command: ["/app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
