"""Create Salary model

Revision ID: 718bedd9a0ec
Revises: bf1236525da9
Create Date: 2023-06-18 16:13:31.268935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718bedd9a0ec'
down_revision = 'bf1236525da9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salary_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'salary', ['salary_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'salary_id')
    # ### end Alembic commands ###
