"""Create Salary model

Revision ID: bf1236525da9
Revises: f82da5abebaa
Create Date: 2023-06-18 16:10:22.840220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1236525da9'
down_revision = 'f82da5abebaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
