"""Fix date naming

Revision ID: b06dbf929a15
Revises: a8a45a0ee338
Create Date: 2023-06-18 19:10:10.195082

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b06dbf929a15'
down_revision = 'a8a45a0ee338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'date_on_next_increase', sa.Date(), nullable=False))
    op.drop_column('user', 'date_of_next_increase')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_next_increase',
                  sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('user', 'date_on_next_increase')
    # ### end Alembic commands ###
